resources:
  repositories:
    - repository: temp
      name: temp
      ref: refs/heads/main
      type: git
pool:
  name: default

steps:
  - checkout: self
    clean: true
    path: s
  - checkout: temp
    clean: true
    path: s/Copy
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/result'